// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Account struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Employee struct {
	ID           int32  `json:"id"`
	EmployeeName string `json:"employee_name"`
}
